/**:
  ros__parameters:
    # pcd_paths_or_directory: ['']
    # pcd_metadata_path: ''

    enable_whole_load: true
    enable_downsampled_whole_load: true
    enable_partial_load: false
    enable_differential_load: true
    enable_selected_load: false

    # only used when downsample_whole_load enabled
    leaf_size: 0.5 # downsample leaf size [m]
    use_sim_time: true